[package]
name = "rustkv"
version = "0.1.0"
edition = "2024"

[dependencies]
# bincode = "3.0.0"
fxhash = "0.2.1"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.148"
tokio = { version = "1.49.0", features = ["full"] }
